let textEmoji = [
  `(⌒▽⌒)`,
  `（￣▽￣）`,
  `(= ・ω・ =)`,
  `(｀・ω・ ´)`,
  `(〜￣△￣)〜`,
  `(･∀･)`,
  `(°∀°)ﾉ`,
  `(￣3￣)`,
  `╮(￣▽￣)╭`,
  `(´_ゝ｀)`,
  `("▔□▔)/`,
  `(ﾟДﾟ≡ﾟдﾟ)`,
  `!?Σ(ﾟдﾟ;)`,
  `Σ(￣□￣||)`,
  `(´；ω；\`)`,
  `（/TДT)/`,
  `(｡･ω･｡)`,
  `(ノ≧∇≦) ノ `,
  `(´･_･\`)`,
  `(-_ -#)`,
  `（￣へ￣）`,
  `(￣ε(#￣) Σ`,
  `ヽ (\`Д´)ﾉ`,
  `(╯° 口 °) ╯(┴—┴`,
  `_(:3」∠)_`,
  `┌(ಠ_ಠ) ┘`,
  `٩͡[๏̯͡๏]۶`,
  `٩(×̯×)۶`,
  `´_ゝ｀`,
  `（｀へ ´）`,
  `🙄`,
  `🙃`,
  `😀`,
  `😏`,
  `😉`,
  `🤗`,
  `👻`,
  `🤕`,
  `🤒`,
  `😎`,
  `🤓`,
  `💩`,
  `😤`,
  `🍵`,
  `💊`,
  `🐸`,
  `🐶`,
  `🐑`,
  `🌝`,
  `🌚`,
  `✨`,
  `💦`,
  `🍭`,
  `🎲`
];

textEmoji = textEmoji.map(emoji => ({ text: emoji, value: emoji }));

let weiboEmoji = [
  "74/moren_hashiqi_thumb.png",
  "09/pcmoren_tanshou_thumb.png",
  "08/dorahaose_org.gif",
  "c7/dorahaipa_org.gif",
  "f0/dorachijing_org.gif",
  "61/dorahan_org.gif",
  "34/xiaoku_org.gif",
  "09/pcmoren_tanshou_org.png",
  "74/moren_hashiqi_org.png",
  "b6/doge_org.gif",
  "4a/mm_org.gif",
  "9e/jqmweixiao_org.gif",
  "89/hufen_org.gif",
  "ac/smilea_org.gif",
  "0b/tootha_org.gif",
  "6a/laugh.gif",
  "14/tza_org.gif",
  "af/kl_org.gif",
  "a0/kbsa_org.gif",
  "f4/cj_org.gif",
  "6e/shamea_org.gif",
  "c3/zy_org.gif",
  "29/bz_org.gif",
  "71/bs2_org.gif",
  "6d/lovea_org.gif",
  "9d/sada_org.gif",
  "19/heia_org.gif",
  "8f/qq_org.gif",
  "b6/sb_org.gif",
  "58/mb_org.gif",
  "17/ldln_org.gif",
  "98/yhh_org.gif",
  "6d/zhh_org.gif",
  "a6/x_org.gif",
  "af/cry.gif",
  "73/wq_org.gif",
  "9e/t_org.gif",
  "f3/k_org.gif",
  "27/bba_org.gif",
  "7c/angrya_org.gif",
  "5c/yw_org.gif",
  "a5/cza_org.gif",
  "70/88_org.gif",
  "e9/sk_org.gif",
  "24/sweata_org.gif",
  "7f/sleepya_org.gif",
  "6b/sleepa_org.gif",
  "90/money_org.gif",
  "0c/sw_org.gif",
  "40/cool_org.gif",
  "8c/hsa_org.gif",
  "49/hatea_org.gif",
  "36/gza_org.gif",
  "d9/dizzya_org.gif",
  "1a/bs_org.gif",
  "62/crazya_org.gif",
  "91/h_org.gif",
  "6d/yx_org.gif",
  "89/nm_org.gif",
  "40/hearta_org.gif",
  "ea/unheart.gif",
  "58/pig.gif",
  "d6/ok_org.gif",
  "d9/ye_org.gif",
  "d8/good_org.gif",
  "c7/no_org.gif",
  "d0/z2_org.gif",
  "40/come_org.gif",
  "d8/sad_org.gif",
  "91/lazu_org.gif",
  "c4/liwu_org.gif"
];

let weiboURLBase = 'https://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/';

weiboEmoji = weiboEmoji.map(url => ({
  url: weiboURLBase + url,
  value: `![](${weiboURLBase + url})`
}));

export default [
  {
    name: '微博',
    emojis: weiboEmoji,
  },
  {
    name: '颜文字',
    emojis: textEmoji,
  }
];